### ISSUE TITLE
Add support for OracleLinux

### ISSUE THREAD

**Issue by AloisMahdal** [beakerlib/beakerlib#100]
Context
=======

We'd like to run some of our existing test code on OracleLinux.  So far we aim for OracleLinux 7/8/9.

Problem
=======

To my knowledge, BeakerLib does not support OracleLinux.  Where this definitely matters is `rlIs*()` family
of functions but there might be more places.

Solution
========

Ideally we'd

 1. In ourt test code, replace all of our `rlIsRHEL()` with a generic function as suggested in #47 and #95,
 2. make sure that this generic function also supports OracleLinux.

so for the matter, I'd consider this RFE to be blocked on one of the other RFE's (they look like dupes).

That said, there could be more places where the RHEL-fork-ness matters so this Solution might not be complete.

**Comment by AloisMahdal** [comment]
FWIW, here's some distro id files from OL 7.9.  (in about a week or so I should also be able to provide 8.y versions)

/etc/os-release

    NAME="Oracle Linux Server"
    VERSION="7.9"
    ID="ol"
    ID_LIKE="fedora"
    VARIANT="Server"
    VARIANT_ID="server"
    VERSION_ID="7.9"
    PRETTY_NAME="Oracle Linux Server 7.9"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:oracle:linux:7:9:server"
    HOME_URL="https://linux.oracle.com/"
    BUG_REPORT_URL="https://bugzilla.oracle.com/"

    ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
    ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
    ORACLE_SUPPORT_PRODUCT="Oracle Linux"
    ORACLE_SUPPORT_PRODUCT_VERSION=7.9

/etc/oracle-release

    Oracle Linux Server release 7.9

/etc/system-release-cpe

    cpe:/o:oracle:linux:7:9:server

/etc/rpm/macros.dist

    # dist macros.

    %rhel 7
    %dist .el7
    %el7 1
    %oraclelinux 7
    %ol7 1

/etc/redhat-release

    Red Hat Enterprise Linux Server release 7.9 (Maipo)

/etc/system-release is empty.

**Comment by AloisMahdal** [comment]
So I've got 8.3 as well:

/etc/os-release

    NAME="Oracle Linux Server"
    VERSION="8.3"
    ID="ol"
    ID_LIKE="fedora"
    VARIANT="Server"
    VARIANT_ID="server"
    VERSION_ID="8.3"
    PLATFORM_ID="platform:el8"
    PRETTY_NAME="Oracle Linux Server 8.3"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:oracle:linux:8:3:server"
    HOME_URL="https://linux.oracle.com/"
    BUG_REPORT_URL="https://bugzilla.oracle.com/"

    ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
    ORACLE_BUGZILLA_PRODUCT_VERSION=8.3
    ORACLE_SUPPORT_PRODUCT="Oracle Linux"
    ORACLE_SUPPORT_PRODUCT_VERSION=8.3

/etc/oracle-release

    Oracle Linux Server release 8.3

/etc/system-release-cpe

    cpe:/o:oracle:linux:8:3:server

/etc/rpm/macros.dist

    # dist macros.

    %rhel 8
    %dist .el8
    %el8 1
    %oraclelinux 8
    %ol8 1

/etc/redhat-release

    Red Hat Enterprise Linux release 8.3 (Ootpa)

/etc/system-release is symlinked to oracle-release.

**Comment by StykMartin** [comment]
+1 on OracleLinux support. 
I can provide additional data if needed.

**Comment by sopos** [comment]
The plan was to implement rlIsOS and rlIsOSLike as described in https://github.com/beakerlib/beakerlib/issues/47#issuecomment-557101036
Using the `rlIsOSLike` would allow to merge similar distros but _Oracle_ uses different versioning schema than _Fedora_ which is is _like_.

At the same time we cannot support all the possible distros in the core beakerlib. We need to find some reasonable compromise.
