### ISSUE TITLE
rlImport should check that the callback function exists and raise better error

### ISSUE THREAD

**Issue by jscotka** [beakerlib/beakerlib#102]
when doing some new library with copying lib.sh sources from another library I've  was unable to debug the the issue
```
:: [ 04:43:48 ] :: [   FAIL   ] :: Command 'rlImport cockpit/atomicstart' (Expected 0, got 1)
:: [ 04:43:48 ] :: [  ERROR   ] :: rlImport: Import of library cockpit/atomicstart was not successful (callback failed)
```
after @sopos investigation He found that I did not chaged: `#   library-prefix = cockpit`
so that it did not called proper callback function.  and also output is that just show that `callback failed`, and it seems that there is some error inside this function.

So there should be better message in this case and show that there is not defined proper callback function,  and what is expected like
```
:: [ 04:43:48 ] :: [  ERROR   ] :: rlImport: Import of library cockpit/atomicstart was not successful (missing callback function cockpitLibraryLoaded in lib.sh file (or defined  library prefix is bad see #   library-prefix = cockpit))
```

**Comment by sopos** [comment]
implemented by https://github.com/beakerlib/beakerlib/pull/105
