### ISSUE TITLE
Can you build the beakerlib at a Fedora GA time (or slightly before)?

### ISSUE THREAD

**Issue by praiskup** [beakerlib/beakerlib#103]
First, I have to admit that I'm from the Copr maintenance team, and we are
using beakerlib for testing Copr.  So I might be a bit biased, but still.

We use a container environment to run our integration testing that
is using beakerlib - and we try to move from Fedora N to Fedora N+1
usually very soon, when the `N+1` release is out.  But our processes
always choke on the [/etc/yum.repos.d/beaker-client-Fedora.repo](https://beaker-project.org/yum/beaker-client-Fedora.repo)
file.  It usually takes too much time till the new Fedora repository
starts working (e.g. F34 is still not available at this point in time).

In Fedora Copr, there's the "follow fedora branching" option which
would automatically create Fedora N+1 repository for you (and us,
users) at (almost) appropriate time.

**Comment by sopos** [comment]
Currently, we use packit to create builds on PRs and master branch. That is not enough for you?

**Comment by praiskup** [comment]
Not really, we don't want to consume pre-release beakerlib.

**Comment by praiskup** [comment]
Well, at least - it would be nice if you could build the beakerlib at the point
when Fedora N+1 is GA, or a bit earlier so the migration is flunt (we've had
these issues for like dozen of Fedora releases so far).

**Comment by sopos** [comment]
I'm not that familiar with copr and I do not want to maintain another build system. Is it possible to test it up so it is more or less transparent to me?
I guess the current packit configuration should be enough to use it as a base. Just point me to the step-by-step guide how to set it up.

**Comment by praiskup** [comment]
> Is it possible to test it up so it is more or less transparent to me?

Yes, since you already build the software using Packit, it should be pretty transparent.  The only
difference is that you need - during release time - submit a build like `copr build <your-project> <new.src.rpm>`.

There's the quick start document: https://docs.pagure.org/copr.copr/user_documentation.html#quick-start

**Comment by praiskup** [comment]
If you wanted a namespace like `beakerlib/stable`, there's a documentation:
https://docs.pagure.org/copr.copr/user_documentation.html#how-can-i-create-new-group

Feel free to contact me (praiskup) on irc (#fedoíra-buildsys on libera.chat and freenode)
and I can help you with onboarding.

> I'm not that familiar with copr and I do not want to maintain another build system

Of course, no problem if you don't use Copr - the real reason for this request is to
have an official build of beaker soon enough in the next fedora releases.

**Comment by praiskup** [comment]
Can you please build for Fedora 35?

**Comment by praiskup** [comment]
(it's not a GA time yet, though builds are already possible - and would be useful)

**Comment by sopos** [comment]
I'm out till next Monday. @hegerj, are you able to make a build?

**Comment by hegerj** [comment]
If you mean official Koji build then I am afraid I can't.
I built one in copr, not sure it is enough for you https://copr.fedorainfracloud.org/coprs/jheger/beakerlib/build/2525211/

**Comment by sopos** [comment]
I can see a releng build [1] already, so there's probably no needed to do another one..

1. https://koji.fedoraproject.org/koji/buildinfo?buildID=1784686

**Comment by sopos** [comment]
@praiskup, Anyway, why the standard mass-rebuild is not enough? Normally it happens automatically. Or do you need beakerlib to be ready before the mass-rebuild happens? There may be some mechanism to rebuild some packages first..

**Comment by praiskup** [comment]
Well, what I wanted to talk about is https://beaker-project.org/yum/beaker-client-Fedora.repo

It points to https://beaker-project.org/yum/client-testing/ repository, which doesn'ŧ even have the F34, yet.

**Comment by praiskup** [comment]
Btw., we depend on rhts-test-env package, which e.g. some of our internal toolings depends on.  But it si not available anywhere else (soon enough).

**Comment by praiskup** [comment]
@sopos informed me that `rhts-*` shouldn't be needed nowadays in our testsuite, we'll do something about it.

As I understand it, the https://beaker-project.org/download.html isn't under beakerlib's maintainers' control ... so the
report here was in the wrong place since the beginning.
