### ISSUE TITLE
[RFE] Option for rlFileSubmit to gzip file

### ISSUE THREAD

**Issue by lukaszachy** [beakerlib/beakerlib#137]
There is rlBunleLogs which creates a tarball and uploads it however gzip is more user friendly for single file use case as zcat/zgrep exist.

Use case `rlFileSubmit <long_text_log> --gz` and later one can cat/grep that file using zcat/zgrep without extracting it.

Currently one has to `rlBundleLogs <tarball_name> <long_text_log>` and `tar xOzf`  to pipe to stdout.

**Comment by sopos** [comment]
The idea of the `rlFileSubmit` is also to be able to open the file directly in the web brower while the files are put to some log retention. Such storage may use online compression to actually handle the disk space more efficiently. 

For this specific case I'm not really open to implement it as the trivial workaround would be like this:
```
gzip [-k] long_text_log
rlFileSubmit long_text_log.gz
```
I don't see much difference in changing a test by adding `--gz` or `gzip -k file`. A change of a test would be necessary anyway.
