### ISSUE TITLE
rlFetchSrcForInstalled should prioritize --source repo before Koji

### ISSUE THREAD

**Issue by kkaarreell** [beakerlib/beakerlib#145]
If SRPM is available in a source repository it should be the first place to look for. Not just that it seems a natural choice but also a tester could modify tested artifacts prior running a test while making them available from a custom repository.

Also, it would speed up SRPM download when SRPM cannot be found in Koji (e.g. for CentOS Stream).

**Comment by hegerj** [comment]
I'll be honest I do not fully understand this issue (and cursory look at the code didn't help much :) ), but what would be the downside of switching to "yum direct" order? 
From what you wrote it sounds like it would solve @kkaarreell's problem and "direct" method would still retain functionality under some use cases.

**Comment by sopos** [comment]
I see the _direct_ method faster than the _yum_ method. The _yum_ may be more accurate so I would lean towards switching the order.
It should not break any use-case. At least, I'm not able to come up with some which would break.

**Comment by hegerj** [comment]
I agree with the switching of the order.

**Comment by sopos** [comment]
fixed by https://github.com/beakerlib/beakerlib/commit/cc6d87f2d601305f4470d70b16e3218ce435650b
