### ISSUE TITLE
Man beakerlib disappeared 

### ISSUE THREAD

**Issue by fhrdina1** [beakerlib/beakerlib#162]
It was presented  [here](https://github.com/beakerlib/beakerlib/wiki/man) but for some time I have been getting only "Sorry, there was an error rendering this page."

**Comment by sopos** [comment]
Thanks for the heads up, I will add a link to the new location https://beakerlib.readthedocs.io/en/latest/manual.html

**Comment by fhrdina1** [comment]
Great, thank you.

**Comment by sopos** [comment]
Seems the web parser stopped to work even though the data was there. Anyway, it was kinda outdated while the [readthedocs](https://beakerlib.readthedocs.io/en/latest/manual.html) is the latest super trouper shiny one.
