### ISSUE TITLE
Wiki page got  "Sorry, there was an error rendering this page."

### ISSUE THREAD

**Issue by FineFan** [beakerlib/beakerlib#163]
Hey guys,

The wiki man page : https://github.com/beakerlib/beakerlib/wiki/man
Got  "Sorry, there was an error rendering this page."

**Comment by sopos** [comment]
Removed that page. It was moved to [readthedocs](https://beakerlib.readthedocs.io/en/latest/manual.html).

**Comment by hegerj** [comment]
I have fixed the link in Wiki and added link to the removed page.
