### ISSUE TITLE
rlFileSubmit should copy files to TMT_PLAN_DATA in case of tmt

### ISSUE THREAD

**Issue by pellecchialuigi** [beakerlib/beakerlib#168]
Running a test via tmt, beakerlib should be able to automatically copy files to the path defined by the environment variable TMT_PLAN_DATA.

Checking that variable can be a way to understand if a test has been executed via tmt.

**Comment by sopos** [comment]
The _beakerlib_ is primarily focused on the beaker and so it checks beaker-like variables. The `tmt` sets the respective beaker-like variables if the test `framework` is set to _beakerlib_. Does your test specify the beakerlib framework?
AFAIK, _tmt_ should be covering it already. @psss, @lukaszachy can you confirm that?

**Comment by lukaszachy** [comment]
rlFileSubmit copies to TMT_TEST_DATA.

which is not set/available in prepare or finish steps

**Comment by lukaszachy** [comment]
To be more precise: for 'beakerlib' framework tmt sets `BEAKERLIB_DIR` and `BEAKERLIB_COMMAND_SUBMIT_LOG` variables.  The later point to `tmt-file-submit` script which uses 'TMT_TEST_DATA' variable as location to put any files in.

IMO there is no need for beakerlib to be aware of 'tmt' or any other executors, there is already plenty of variables to set if necessary.

@pellecchialuigi Could you be more verbose about your use case which lead to this issue? All what I can think of is https://github.com/teemtee/tmt/issues/969

**Comment by pellecchialuigi** [comment]
Hi all, and sorry for the late feedback. I'm running some beakerlib based tests with tmt and I had to access some artifacts that were handled with the rlFileSubmit. I wasn't aware about the integration from the tmt side, I was looking in something inside the beakerlib code. As long as tmt allow to retrieve the artifacts I think we can close this issue.
Thanks both for your kind support and all the explainations.
