### ISSUE TITLE
beakerlib-journaling takes too long for larger journals

### ISSUE THREAD

**Issue by rfmvh** [beakerlib/beakerlib#18]
The operation below takes tens of minutes or sometimes even an hour to finish with larger journals:
`/usr/bin/beakerlib-journalling --metafile journal.meta --journal journal.xml`
The older beakerlib did not suffer from this, or at least it seemed so. Thanks.

**Comment by sopos** [comment]
If the logged message if huge, meaning tenths of megabytes, the processing is really slow. There are possible places, one is base64 which is less probable, the second one is xml parser. Old journalling used to use minidom while the new one uses lxml. Maybe lxml has problems with handling that big data. We need to investigate it more deeply.

**Comment by hegerj** [comment]
@rfmvh  Hi, I discovered the problem, it was with shlex module. I've replaced shlex and it should be faster. 
Could you please try to run the test again?

**Comment by sopos** [comment]
closing this issue as it should be fixed by https://github.com/beakerlib/beakerlib/commit/a418f06c9d381d89b248bc22a293787ebcc59ef4
