### ISSUE TITLE
Set LibraryDir earlier

### ISSUE THREAD

**Issue by AloisMahdal** [beakerlib/beakerlib#29]
Currently LibraryDir is set during LibraryLoaded, which makes it impossible to use it in context like defining of global variables:

For example, where ns-prefix is `distribution_hack__`:

    distribution_hack__path=${distribution_hack__path:-$distribution_hack__LibraryDir/hacks}

This should set the path global to 'hacks' sub-directory, but it won't works because the LibraryDir is not set.  It should be possible to find it out already; it's just dirname of file we're reading.

**Comment by sopos** [comment]
The description is a bit misleading but based on the summary I think I got your point. Fixed by https://github.com/beakerlib/beakerlib/commit/1466df87aa12df371c4335215f0bb90b7e9da123.

**Comment by AloisMahdal** [comment]
Indeed, thanks!
