### ISSUE TITLE
[RFE] Final Pass/Fail report missing consolidated results

### ISSUE THREAD

**Issue by bhavikbhavsar** [beakerlib/beakerlib#30]
Final report doesn't contain consolidated test result.
Below image shows how it used to generate the consolidated test results before.
![image](https://user-images.githubusercontent.com/4545441/39300026-fdf56b92-4967-11e8-985d-4ca7ed84ec1b.png)

and how it looks like now:
![image](https://user-images.githubusercontent.com/4545441/39427005-be455f80-4c9f-11e8-8242-cbf8b818ebd8.png)

As per the email communication: 

> your test / library parses those data form the text journal form which was redesigned a bit. This text form was never meant to be machine processed. It would be better to go other way. There's a results file referenced by __INTERNAL_TEST_RESULTS, where those information might be available to you. Unfortunately it appears to be still undocumented.

Hence filing this RFE.

**Comment by sopos** [comment]
To be clear we are not willing to revert the text (human readable) output format.
Therefore an update of your test / library is necessary to collecting data from correct stable source.

The RFE should be mainly against the missing data in results file.

I guess the first step is to properly document the results file.
Next step is to identify needed data.
Then to implement the actual RFE.
And finally you can update your test / library to reflect that.

**Comment by bhavikbhavsar** [comment]
Thanks @sopos,
Could you please let me know what is required to properly document the results file or what change do we need to make to get it back to working? 
This problem affects whole of identity management team. Because most of our tests are in beaker.

**Comment by sopos** [comment]
@bhavikbhavsar I was badly looking at the documentation. It is already documented. You can see it in TestResults section of `man beakerlib`.
What you need is to source file `$BEAKERLIB_DIR/TestResults` after rlJournalEnd is called. Than you can use those documented variables.

If you miss some important data there, or it does not fit you workflow, reopen this issue with particular request.
