### ISSUE TITLE
Invalid literal for int()

### ISSUE THREAD

**Issue by mkutlak** [beakerlib/beakerlib#38]
I am getting this error on Fedora 29+.
```
Failed to convert timestamp attribute to int.                        
Error: invalid literal for int() with base 10: '"1538625769"'
Exiting unsuccessfully.
```
Looks like quotes are not striped from the `attribute_value` variable.

Suspect:
https://github.com/beakerlib/beakerlib/blob/3f0aca9c08fccdc00193169dd3a591844203f851/src/python/journalling.py#L134

**Comment by hegerj** [comment]
This is an issue with Fedora package which mixed journal.sh and journalling.py from different upstream branches (probably patching error).
It's not an issue with upstream. Version from master or devel branches work on Fedora 29 fine (afaik).
