### ISSUE TITLE
getting "Option -T deprecated! Update your code." when under restraint

### ISSUE THREAD

**Issue by AloisMahdal** [beakerlib/beakerlib#39]
Most, if not all our `taskout.log`'s are filled with these:

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    ::   /distribution/crashes/check-abrt
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

    ** (rstrnt-report-log:21753): WARNING **: ...: Option -T deprecated! Update your code.

    Uploading journal.xml 

Versions:

    beakerlib-1.17-13.el7bkr.1.noarch

**Comment by sopos** [comment]
I'm not sure if removing the -T options is not problem for rhts_submit_log. I need to discuss it with its devels.

**Comment by AloisMahdal** [comment]
I think the issue is that while BEAKERLIB_COMMAND_SUBMIT_LOG can be changed, it should never be changed to something with different CLI; for different harness, things could go way more haywire than this.

Just a thougt about quick-ish fix: provide internal wrapper that will "ifdef" to proper beah/rhts/restraint/whatever?

**Comment by sopos** [comment]
The too provided via the variable should be kept compatible. If restraint and rths should be in sync in this. Otherwise, we need to come up with some better solution, something similar to a drop-in *.d config dir or a template style of setting this.

**Comment by sopos** [comment]
fixed by 01d3445a1798b20b4fd452c2fb7691b8dd35245c
