### ISSUE TITLE
rlFileSubmit prints stuff to stdout

### ISSUE THREAD

**Issue by AloisMahdal** [beakerlib/beakerlib#40]
`rlFileSubmit` will print things like "Uploading ... .done" to stdout, which breaks use cases where stdout is being generated and needs to have proper format. (E.g. meta-programming.)

Reproduced with local build: beakerlib-1.17-13.el7bkr

**Comment by hegerj** [comment]
This is not in control of rlFileSubmit / beakerlib. Beakerlib calls script supplied by harness:
/usr/bin/rhts-submit-log in case of beah
/usr/bin/rstrnt-report-log in case of restraint

**Comment by sopos** [comment]
One think we could do on our side is to redirect the output of the command to stderr. I'm not sure if that's the correct approach, though.

**Comment by AloisMahdal** [comment]
Thanks, reported to [p3ck/restraint](https://github.com/p3ck/restraint/issues/37).

@sopos, it would be definitely better if restraint did it.  I'd leave redirection on beakerlib part only as a workaround in case the fix would take too long.
