### ISSUE TITLE
Can't use `set -u` in test scripts

### ISSUE THREAD

**Issue by larskarlitski** [beakerlib/beakerlib#43]
beakerlib uses some unbound variables which makes it impossible to run with `set -u`:

```
$ cat test.sh 
set -u

. /usr/share/beakerlib/beakerlib.sh

$ sh test.sh 
./beakerlib.sh: line 34: __INTERNAL_SOURCED: unbound variable
posix          	on
./infrastructure.sh: line 987: BEAKERLIB_DIR: unbound variable
```

CC @atodorov

**Comment by sopos** [comment]
should be now fixed by https://github.com/beakerlib/beakerlib/commit/1ee8383ff6108273a0bd726e8ccddbdaa43956b9

**Comment by sopos** [comment]
we found few more variables, so fixing by https://github.com/beakerlib/beakerlib/commit/57ad9345c5fb4d893de7a969c7a83826c4476a93

**Comment by larskarlitski** [comment]
It might be useful to have a test to make sure that this doesn't regress.

**Comment by sopos** [comment]
It is hard to find all the variables without actually executing all the code. The only way to test it is to run whole test suite with set -u enabled.
