### ISSUE TITLE
Bad rlGetDistroVariant() letter case on ComputeNode

### ISSUE THREAD

**Issue by AloisMahdal** [beakerlib/beakerlib#44]
On RHEL-6 (and probably other) `ComputeNode`, `rlGetDistroVariant` will print `Computenode` which is incorrectly cased.

This can lead to further errors reading variant-named artifacts or URL's containing variant.

---

Apparently the error is caused by this naive attempt to "fix" casing:

     rpm -q --qf="%{NAME}" --whatprovides redhat-release | cut -c 16- | sed 's/.*/\u&/'

This is a solution that gets casing right (for one-letter variants, anyway (which are all RHEL-6 variants)):

     grep -Eoe "Linux [^ ]+ release" /etc/system-release | cut -d' ' -f2

Note that for RHEL-7 and above (or any systemd distros), it makes most sense to read VARIANT key from /etc/os-release using function like this:

    __eor_key() {
        #
        # Read key $1 from /etc/os-release
        #
        # /etc/os-release supports syntax similar to shell assignment,
        # so we'll run it in a sandbox.
        #
        local key=$1
        test -f "/etc/os-release" || return 2
        ( eval "$(grep -m1 "^$key=" /etc/os-release); echo \$$key"; )
    }

called:

>     $ __eor_key VARIANT
>     ComputeNode

**Comment by sopos** [comment]
should be fixed by https://github.com/beakerlib/beakerlib/commit/804a7b4672db6e3eaeae9aabab301d5b49478661
