### ISSUE TITLE
[idea] rlIsEL macro to match both rhIsRHEL and rlIsCentOS

### ISSUE THREAD

**Issue by hhorak** [beakerlib/beakerlib#47]
This is caused by how the macro is implemented:
https://github.com/beakerlib/beakerlib/blob/eb3f87355ec8d96c0850882333ba8b83c1c6b972/src/testing.sh#L1318-L1320

I guess many tests use just `rhIsRHEL`, but the tests should work fine on all clones, like CentOS or even other. It would be nice to have a macro that matches all such clones, so even users of Scientific Linux or Oracle Linux can contribute with tests (in epel for example).

**Comment by sopos** [comment]
Thanks for the report. This is good idea.
We also plan to rework the distro identification and getting a version so it would make sense to implement it after the new code is ready.

**Comment by AloisMahdal** [comment]
Changing meaning of `rlIsRHEL` to also match CentOS would break our tests; OTOH adding something more generic could be helpful.

**Comment by sopos** [comment]
I wonder what to use to reliably identify such EL distro..

**Comment by hegerj** [comment]
I am against the original issue for reasons @AloisMahdal mentioned. The simple solution for it is to make the condition `rlIsRHEL || rlIsCentOS`.

As for the rlIsLike function 'ID_LIKE' doesn't seem very reliable to me. 
What if rlIsLike would be just wrapper for combinations of rlIsRhel/rlIsCentOS/rlIsFedora which would return true for different arguments? This would however not work for other distros (like Scientific Linux).

**Comment by sopos** [comment]
The original request is not about changing rlIsRHEL behaviour. It is about adding to function. In that sense I would go by more generic way which might be something based on /etc/os-release data. Regarding to this I could imagine functions `rlIsDisto` and `rlIsDitroLike`. Current function could evolve to some wrappers around them. Anyway I would like to see the /etc/os-release files from different distros to see if it is a suitable way. 

There's also another question about the versionning. In case of CentOS vs RHEL it is the same. I'm not sure about Scientific or Oracle versionning, though. As rlIsRHEL can normally take version specification to match against it would be necessary to also reasonable requirement for the function to provides comparable version matching. It that's not possible then it would not make sense to have such function.

**Comment by martinky82** [comment]
I suggest this approach:

implement switch in rlIsRHEL (via env variable or similar) which allows relaxing its behaviour as follows:
 - default is current behaviour
 - if requested, rlIsRHEL behaves on RHEL clones as it would on RHEL itself (rhIsRHEL 8 passes on CentOS 8 or OEL 8)

**Comment by martinky82** [comment]
+rlIsRHELLike() {
+    #
+    # True if rlIsRHEL $@ OR rlIsCentOS $@ would be true
+    #
+    rlIsCentOS "$@" && return 0
+    rlIsRHEL   "$@" && return 0
+    return 1
+}

**Comment by t184256** [comment]
How is that better than a separate command? I see rlIsRHEL doing not what it says on the tin as a downside.

**Comment by sopos** [comment]
> How is that better than a separate command? I see rlIsRHEL doing not what it says on the tin as a downside.

This is related to the env varialble mentioned in https://github.com/beakerlib/beakerlib/issues/47#issuecomment-819477481, istn't it?

**Comment by t184256** [comment]
Yes, that was meant to refer to that comment, sorry for confusion.

**Comment by sopos** [comment]
> Yes, that was meant to refer to that comment, sorry for confusion.

Well, there are pros and cons, of course.
Imagine the situation they want to run Tier tests for many components on some _RHEL_ clone, e.g. _CentOS_. Using some environment setting (the global variable) they could make those tests to thing they run on RHEL.
This may be useful in the situation they would like to somehow migrate from e.g. _CentOS_ to _RHEL_. Meaning they would like to run the tests before the migrate and after it to make sure the migration went well.

**Comment by sopos** [comment]
I noticed that CentOS does not give minor version on `/etc/os-release` while it does in `/etc/redhat-release`. This can make some troubles. If we want to treat CentOS as similarly to RHEL we will probably need to parse the `/etc/redhat-release` as well to get complete information. For CentOS 7 I can see even numbers like `7.6.1810`. So it get even more complicated.
