### ISSUE TITLE
rlImport imports other libraries

### ISSUE THREAD

**Issue by AloisMahdal** [beakerlib/beakerlib#50]
I came upon this strange behavior in `beakerlib-1.18-7.el7bkr`.

I'm writing a library, say, `d/foo` that needs to import another one, say, `d/bar` opportunistically.  That is, under (and *only* under) certain circumstances, `d/foo` can import `d/bar.

    if test d_bar__var == ok; then
        rlImport d/bar
        d_bar__call ..
    fi

So in my `d/foo` `Makefile` I have

    ...
    @echo "RhtsRequires:    library(d/bar)" >> $(METADATA)
    ...

And in my `runtest.sh` I have just

    rlImport d/foo

The thing is, when I run my test, beakerlib seems to be importing `d/bar` right away!  This of course fails on validation as the circumstances where `d/bar` is valid aren't met.

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    ::   init
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

    :: [ 15:42:30 ] :: [   INFO   ] :: rlImport: Found 'd/foo' in /mnt/tests
    :: [ 15:42:30 ] :: [   INFO   ] :: rlImport: Will try to import d/foo from /mnt/tests/CoreOS/d/Library/foo/lib.sh
    :: [ 15:42:30 ] :: [   INFO   ] :: rlImport: Found 'd/bar', version '17.4-15' in /mnt/tests
    :: [ 15:42:30 ] :: [   INFO   ] :: rlImport: Will try to import d/bar from /mnt/tests/CoreOS/d/Library/bar/lib.sh
    :: [ 15:42:31 ] :: [  ERROR   ] :: d_bar error!
    :: [ 15:42:31 ] :: [   FAIL   ] :: (INTERNAL TEST ERROR) 
    :: [ 15:42:31 ] :: [  ERROR   ] :: rlImport: Import of library d/bar was not successful (callback failed)
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

**Comment by sopos** [comment]
This behaviour is intended. May be the documentation could be better in this regard. `rlImport` first gathers all the requirements and sub-requirements and then import them all. A library should not normally need to call `rlImport` inside it.

**Comment by AloisMahdal** [comment]
I'm baffled.  That's just not how "libraries" work.  Has this been discussed anywhere?

I propose reverting this.

**Comment by sopos** [comment]
This behaviour is there from beginning. It was implemented by @petr-muller at that time. I'm not sure what the discussions were regarding this automatic dependency resolution.
I think the idea behind it is that the required library needs to be imported to successfully import the library itself.

**Comment by petr-muller** [comment]
¯\_(ツ)_/¯

**Comment by AloisMahdal** [comment]
OK, so I'm double-baffled now.

I'm pretty sure that it's happened to me several times that after injecting a new dependency, I forgot to add `rlImport` and got bash errors because of that.

So it looks like if this happens, it only happens if both sides of the RPM arrow are libraries, but not if one of them is test.  (Similar inconsistency already exists on the yum part, and the scar tissue in my brain from learning that is still soft, so why I'm surprised...) Looks like I've been adding `rlImport`'s everywhere for nothing, and conditional import never worked.

@petr-muller from 5+ years ago will have to pardon my deep, loud ... `...SIGH...`. :)

Feel free to whatever this ticket now.

**Comment by sopos** [comment]
in case of the test you can simply use `rlImport --all` which will basically act the same as requirements defined in some of the library. The resolution mechanism is the same.
