### ISSUE TITLE
RFE: Make beakerlib Makefile independent

### ISSUE THREAD

**Issue by Athwale** [beakerlib/beakerlib#57]
Since tests are going to be moving away from Makefiles and using fmf, beakerlib functions which depend on Makefiles should be modified to be able to use fmf file if it is available. 
(There will be a period of time with a portion of tests in fmf and a portion in the older Makefile format)
According to a discussion in Testing Tools Notes gdoc these are some examples of such functions:
rlImport --all 
rlCheckMakefileRequires / rlGetMakefileRequirements
rlAssertRequired
There may be more. Current status of required package definition is also being discussed in Jira ticket TT-119.

**Comment by sopos** [comment]
This is definitely thoughtful request, thanks for that.
Any idea how to reliably parse yaml files in pure bash?

**Comment by kkaarreell** [comment]
Be aware that due to inheritance respective attribute may not be defined at the fmf file level and therefore you won't be able to parse it. Actually, libraries should rather call fmf tool directly and read the attribute value from its output.

**Comment by sopos** [comment]
Right, this needs to be wisely thought up. Being dependent on `fmf` and thus hard dependent on python would be too heavy. Moreover here might not be available whole fmf parent structure on the SUT so it seems like `tmt` would need to be able to pass those information to the test other way. I'm thinking of creating a story against `tmt` to pass a condensed metadata relevant to the test.

**Comment by kkaarreell** [comment]
Yes, tmt storing all metadata along with the test when it is being executed seems like a reasonable requirement.

**Comment by psss** [comment]
Generating the file with aggregated metadata should be relatively easy but would have to be handled not only in `tmt` but also in `wow`. Is that right, @lukaszachy? Before we start implementing / looking more into this, a couple of questions:

What is the complete list of the `beakerlib` functions which depend on `Makefile`? Do we really need them? Could we possibly obsolete them in a better way?

For example, how much benefit brings `rlImport --all`? Would it be such a big pain to name the required libraries? The test code could/would be a bit more specific.

Or, for the `rlAssertRequired`, isn't required packages checking something which should be handled outside of the test (by the tool which is preparing the environment for testing) and not duplicated in each and every test again and again?

**Comment by lukaszachy** [comment]
Well, how easy should be to execute tests without TMT? Currently you just install `beakerlib` and run `make` in test directory.
However with all metadata in fmf format you need to have TMT - if we are OK with that - we could change Beakerlib to prefer (yet another) environment variable before reading Makefile - e.g. if variable is set, use data from there otherwise attempt to parse Makefile.
And TMT (and wow) will fill it properly.

Unfortunately checking in test might be necessary due Restraint installing requires before each task, any test can corrupt environment... I ideal world it would be checked in prepare - but you need to trust all tests to not touch rpms at all.

**Comment by Athwale** [comment]
Are there any news about this. The deadlines are inevitably approaching at a steady pace and we would like to be prepared. :D

**Comment by psss** [comment]
Ok, so here's my proposal: I would recommend to forget about `rlImport --all` completely and explicitly name all libraries which test needs. This should not be such a big pain, it's just a one-time test code change and could possibly be done using `sed`. Plus, I'd say this is a little bit cleaner way how to do function import.

For `rlCheckMakefileRequires`, `rlGetMakefileRequirements` and `rlAssertRequired` I would go with what proposed @lukaszachy: The test would receive an environment variable, let's say `BEAKERLIB_TEST_REQUIRES` or something like that, with the list of required packages (wow already sends this to the wrapper) and `beakerlib` would use that one if no Makefile is found. The same variable would be exported by `tmt` when test is executed by it.

What do you say?

P.S. We should also make sure these things work fine with `PACKAGES` and `REQUIRES` variables which are used for parametrizing tests being used for software collections testing.

**Comment by sopos** [comment]
> Ok, so here's my proposal: I would recommend to forget about `rlImport --all` completely and explicitly name all libraries which test needs. This should not be such a big pain, it's just a one-time test code change and could possibly be done using `sed`. Plus, I'd say this is a little bit cleaner way how to do function import.

This is quite ugly change which is at first not backward compatible. At second, it also means to change not only tests but also libraries which depend on other libraries. And thirdly, what I consider the most unfortunate is that this information will need to be put to the fmf and the `{runtest,lib}.sh` at the same time which rise chance of *inconsistency*. While we need to handle libraries specifically, why don't we send the list of those specifically as well?
> 
> For `rlCheckMakefileRequires`, `rlGetMakefileRequirements` and `rlAssertRequired` I would go with what proposed @lukaszachy: The test would receive an environment variable, let's say `BEAKERLIB_TEST_REQUIRES` or something like that, with the list of required packages (wow already sends this to the wrapper) and `beakerlib` would use that one if no Makefile is found. The same variable would be exported by `tmt` when test is executed by it.

While the mechanism is already there for `BEAKERLIB_TEST_REQUIRES` why not do generate `BEAKERLIB_LIB_REQUIRES`?

**Comment by psss** [comment]
Although in general I definitely agree that keeping backward compatibility is a good thing I'm not sure it should be done at all costs. I'm not strictly against implementing `rlImport --all` as well but was pondering whether this is not a good opportunity to clean up this particular concept as I find it better to explicitly list required libraries in the code. I see it similar as `import module` in python versus requires in spec or setup.py. That's why I proposed this here for discussion. Also what should/would be provided in the `BEAKERLIB_LIBRARY_REQUIRES` variable if the library is referenced using the `fmf` id?

**Comment by psss** [comment]
Here's the summary of today's discussion: Rather than introducing new and new environment variables to handle individual test metadata it will be better to provide the whole set of available and aggregated L1 metadata to beakerlib in a yaml file under the `BEAKERLIB_DIR` directory. From there `beakerlib` would pick whatever it needs (and for what it was originally looking into Makefile). Implementation could look like this:

 * `tmt` ... for each test create its results directory under `execute` already before pushing to the guest and create a `metadata.yaml` there

 * `wow` ... encode the L1 metadata with base64 and pass to the wrapper via an environment variable, wrapper would unpack it into a tmp directory and set `BEAKERLIB_DIR` accordingly

@sopos, @lukaszachy, @thrix, please review and confirm this would be a viable solution.

**Comment by sopos** [comment]
Setting BEAKERLIB_DIR needs to be done carefully as it needs to be consistent across reboots. To set it properly it needs to be set similarly to the beakerlib's default if TEST_ID is set, i.e. BEAKERLIB_DIR=/var/tmp/beakerlib-$TEST_ID.
AFAIK TEST_ID comes from test harness so the wrapper should be able to use it.

**Comment by lukaszachy** [comment]
> * `wow` ... encode the L1 metadata with base64 and pass to the wrapper via an environment variable, wrapper would unpack it into a tmp directory and set `BEAKERLIB_DIR` accordingly

OK, but will it be "real" yaml or simplified version similar to the one used by 'detached' executor?

**Comment by psss** [comment]
I would suggest to provide the L1 metadata in full, so real yaml with full aggregated data.

**Comment by lukaszachy** [comment]
> I would suggest to provide the L1 metadata in full, so real yaml with full aggregated data.

Hm, so Beakerlib will need to depend on yaml library or implement it on its own in shell :+1:

**Comment by thrix** [comment]
I have no better idea how to solve it, just pls gzip the metadata before encoding to make it smaller, just in case the metadata would get large in the future

**Comment by sopos** [comment]
Looking from the beakerlib POV I do not care. However, it really makes sense as yaml (text) can be compressed pretty well. In case of `tmt` I hope it is already happening when pushing the work directory to the target system so we are basically talking about the tandem `wow` / `wrapper`.

**Comment by sopos** [comment]
> Hm, so Beakerlib will need to depend on yaml library or implement it on its own in shell +1

Yes, beakerlib will need to be able to read the yaml format. For the initial requirements it will be enough to `grep` the data, I think. But in future a generic yaml parser might be necessary. There are few bashimplementations on github with their limitations. I think those might be good starting point.

**Comment by kkaarreell** [comment]
> I have no better idea how to solve it, just pls gzip the metadata before encoding to make it smaller, just in case the metadata would get large in the future

At which moment such metadata are going to be generated? I thought it would be generated on the target system (test runner) prior the test execution. gzip such data would mean that a beakerlib (or something else) would need to gunzip them again right away for the processing, i.e. no benefit, just wasting the machine time. gzip would only make sense if you are transferring it to the host system (still it seems reasonable to me to store them there extracted)  or submitting it with logs (which you may or may not do, moreover you could compress it prior log submitting anyway).

**Comment by lukaszachy** [comment]
> At which moment such metadata are going to be generated? I thought it would be generated on the target system (test runner) prior the test execution. gzip such data would mean that a beakerlib (or something else) would need to gunzip them again right away for the processing, i.e. no benefit, just wasting the machine time. gzip would only make sense if you are transferring it to the host system (still it seems reasonable to me to store them there extracted) or submitting it with logs (which you may or may not do, moreover you could compress it prior log submitting anyway).

This is just for `wow --fmf` use case, where TMT is not installed on the target system (SUT) so wow will parse the metadata and include it into param element of job.xml. AFAIK there is no other way how to include file into restraint's job.xml acceptable by Beaker.
Gzip+base64 combo is precaution so we don't hit max variable length issue (very unlikely as of now but who knows what users will put into metadata later :)

So to answer - metadata will be generated at the moment when wow creates the job recipe.
Unzip will be responsibility of the wrapper.

**Comment by thrix** [comment]
thanks @lukaszachy 

for explanation of which system runs what, I would use the STI terminology:
https://docs.fedoraproject.org/en-US/ci/standard-test-interface/#_terminology

* `wow --fmf` (beaker job xml generation) is run on test runner
* wrapper script is run in the test environment

**Comment by psss** [comment]
The `tmt` part of the implementation is ready for testing: https://github.com/psss/tmt/pull/386

**Comment by psss** [comment]
The `tmt` part has been merged. You can use the latest build from the copr repo for testing.

**Comment by psss** [comment]
The wow/wrapper part done. Now this is the last remaining piece.

**Comment by psss** [comment]
The incomplete `metadata.yaml` issue has been fixed and merged.

**Comment by thrix** [comment]
Where are we with this feature please? Seems this is one of the main blockers for teams mass migrating tests. @sopos could we somehow prioritize it pls?

**Comment by sopos** [comment]
I'm working on that. Actually the yaml parser [1] is done. Now I just need to include it in beakerlib and make the fallback to the old good Makefile.

1. https://github.com/sopos/yash

**Comment by sopos** [comment]
the PR https://github.com/beakerlib/beakerlib/pull/73 implementing this feature was merged
