### ISSUE TITLE
xUnit Results?

### ISSUE THREAD

**Issue by johnbieren** [beakerlib/beakerlib#6]
Hello,

What would it take to have xUnit results integrated into beakerlib, so that say provided some option, running beakerlib tests would give xUnit output?  Is this a possibility?

Thanks

**Comment by sopos** [comment]
AFAIK Petr Müller have done some work on this topic, I'm not sure the exact state right now.
Anyway we plan to introduce some major changes to journal handling so once we finish that we can move this direction.
The journal change is expected to happen this summer / fall

**Comment by sopos** [comment]
This should be introduced by https://github.com/beakerlib/beakerlib/commit/e88af6f46dec1b8a114d46fdb856612e374f7be8. Current testing branch does include it already.
