### ISSUE TITLE
User friendly way for package NVR comparison

### ISSUE THREAD

**Issue by kkaarreell** [beakerlib/beakerlib#60]
Beakerlib has rlCmpVersion and rlTestVersion, however when one wants to compare NVR of an installed package he needs to:
 - check if the package is installed at first
 - use rpm --query ... to get the package version and pass it as arguments

It would be handy to have functions like rlCmpPkgVersion and rltestPkgVersion that does the above on behalf of the user. It would be called e.g. as follows:
rlCmpPkgVersion bash 1.2-3
rlTestPkgVersion bash 1.2-3

Few more notes:
 - an error should be printed if the package is not installed
 - not sure if Version in the name is appropriate, maybe NVR would be better
 - cannot use simple NVR comparison, imagine the user would provide only Version and still we would like it to work properly, e.g. "rlTestPkgVersion bash 1.2" should return '=' both for bash-1.2-1 and bash-1.2-9. Release should be considered for comparison only if it is provided.

**Comment by sopos** [comment]
I see you point. I think it should not be too difficult to modify the current comparing function to do the partial-version match. At the same time I think it is low prio stuff, right now. To speed it up you can provide a patch or a PR.
Btw, should `rlTestPkgVersion bash 1` be true for bash-1.2 as well?

**Comment by kkaarreell** [comment]
I believe it could encourage people to stop using rlIsRHEL for this purpose and move to this more suitable approach. Using rlIsFedora and rlIsRHEL could become a problem once for tests upstreamed to Fedora.
Regarding the last question, version 1 != 1.2.

**Comment by kkaarreell** [comment]
One more idea, it would be great to be able to define the scope for NVR comparison in a sense that both values being compared must contain the scope as a substring, otherwise the comparison would fail.

Scope would be either: name, version, release, dist,
although my primary focus is no dist right now.

Example/Justification:
I have a fix that is being backported to following RHEL versions where the currently latest versions of the foo packages is:
 * RHEL-8.3 (in development) - foo-2.0-1.el8
 * RHEL-8.2 - foo-1.0-2.el8
 * RHEL-8.1 - foo-1.0-1.el8_1.2  (there was a zstream fix)
Now, let's say I have backported the patch and built following packages
 * RHEL-8.3 - foo-2.0-2.el8
 * RHEL-8.2 - foo-1.0-2.el8_2
 * RHEL-8.1 - foo-1.0-1.el8_1.3 (there were some zstreams already)
Now, when running the test I would like to distinguish not just individual package/RHEL versions, but also deal with a situation when (for a testing purposes) foo-2.0-2.el8 package is installed on RHEL-8.2 (e.g. for testing purposes).
Depending on the actual update schedule, the conditions I could use would be:

`rlCmpPkgVersion foo ">=" "2.0-2"`  would match for that specific package version and anything above. I believe that this would be the most commonly used case, used even when testing 8.3 package installed on the 8.2. release.
`rlCmpPkgVersion foo --dist "el8_2" ">=" "1.0-2.el8_2"`  would match any package update within that particular release stream. With this I can handle a situation when the fix has been backported to a zstream for one release but not to the newer release.
`rlCmpPkgVersion foo --dist "el8_1" ">=" "1.0-1.el8_1.3"` is the same as in the previous case, only for a stream with former zstream updates.

**Comment by kkaarreell** [comment]
Just for completeness, the same job would do a simple substring check done e.g. via
`rlCmpPkgVersion foo --substr "el8_1" foo ">=" "1.0-1.el8_1.3"

or this way
`rlCmpPkgVersion foo --prefix "1.0-1.el8_1" foo ">=" "1.0-1.el8_1.3"

**Comment by sopos** [comment]
I think there might be slight deviation in the format of the release part so I would not complicate it by an attempt to implement a dist parsing. Basically it should be enough something like 
`rlCmpPkgVersion foo "1.0-1.el8_1" && rlCmpPkgVersion foo ">=1.0-1.el8_1.3"`
may be some logical operators could be implemented (might by tricky)
`rlCmpPkgVersion foo "1.0-1.el8_1 && >=1.0-1.el8_1.3"`
the it could be used as
`rlCmpPkgVersion foo "1.0-1.el8_1 && >=1.0-1.el8_1.3" "1.0-2 && >=1.0-2.el8_2"` where logical OR would be between parameters (as it is in rlIsRHEL) while logical AND could be used inside it.

**Comment by kkaarreell** [comment]
The first example you have is wrong according to the NVR aritmetics. 
`"1.0-1.el8_1" < "1.0-1.el8_1.3"` and therefore your condition cannot be True, ever.

**Comment by kkaarreell** [comment]
To clarify my objection a bit more...
Assuming that rlCmpPkgVersion would consider `"1.0-1.el8_1" = "1.0-1.el8_1.3"`, it would imply that `"1.0-1.el8_1.3" = "1.0-1.el8_1.30"`. It is not. ;-)

**Comment by sopos** [comment]
Even the current comparsion  would not match `"1.0-1.el8_1.3" = "1.0-1.el8_1.30"`. But your right, my proposal would work only if `foo 1` would be true for `foo-1.2` which you've already refused.

**Comment by kkaarreell** [comment]
Initial version implemented in https://github.com/beakerlib/beakerlib/pull/64

**Comment by sopos** [comment]
I think this is implemented as a separate beakerlib library https://github.com/beakerlib/nvr/tree/master/nvr
