### ISSUE TITLE
rlCmpVersion do compare letters wrong

### ISSUE THREAD

**Issue by kkaarreell** [beakerlib/beakerlib#63]
I would recommend using rpm.labelCompare instead.

```
$ rlCmpVersion 'ab' 'b'
>
$ python
Python 2.6.6 (r266:84292, Jun 11 2019, 11:01:44) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rpm
>>> rpm.labelCompare(('1','1','ab'), ('1', '1', 'b'))
-1
>>> rpm.labelCompare(('1','1','1'), ('1', '1', '2'))
-1
```

**Comment by kkaarreell** [comment]
Please ignore, I realized that these functions are now following RPM arithmetics.

**Comment by sopos** [comment]
It looks correct to me. Letters are basically interpreted as a base-26 numbers. Here `ab` vs. `b` is a analogy to `12` vs. `2`. Actually the base is here 36 `[0-9a-z]`.
Do I understand it correctly that rpm.labelCompare sorts numbers based on its value, while letters alphabetically?
How to deal with combinations of letters and numbers?
What is bigger `fc1` or `fc31`?

**Comment by kkaarreell** [comment]
Yes, RPMs are being evaluated differently. See e.g.
https://www.thegeekdiary.com/understanding-rpm-versions-and-naming-schemes/
That means that current functions cannot be reliably used for comparing RPM versions.
