### ISSUE TITLE
allow simpler library name

### ISSUE THREAD

**Issue by sopos** [beakerlib/beakerlib#69]
Currently the library name is required to be in format `<COMPONENT>/<LIB_NAME>`. While we enabled libraries to be placed in individual repos on github the names might be simplified as well. E.g. currently there's library `squid/squid` in https://github.com/beakerlib/squid. The name here is forced to be double _squid_.
I think we may ease the requirement for it to be basically any string. If there was `/` the part before first `/` would be treated as a _component_, the rest as a _lib_name_. This would allow one to have a library in the git root and not to be forced to artificially created another names.
For the squid example the library name would be simply `squid`.

@psss, @hegerj, @lukaszachy, any thoughts?

**Comment by hegerj** [comment]
Although `squid/squid` is a silly name I am not sure about changes to things that work :) 
Wouldn't this lead to confusion between upstream/downstream (I expect this change would only happen in new beakerlib library github location)?
Also some libraries will still need full name and some will have just 1 name, which could be also confusing.

**Comment by sopos** [comment]
> Although `squid/squid` is a silly name I am not sure about changes to things that work :)
> Wouldn't this lead to confusion between upstream/downstream (I expect this change would only happen in new beakerlib library github location)?

No necessarily on github but mainly there.

> Also some libraries will still need full name and some will have just 1 name, which could be also confusing.

I'm not sure what confusion you mean. In fact, the library name was always the full string in _library()_ brackects. The change proposal is about a possibility to omit _/something_, the logic would stay the same. Search for the library would work almost the same:
```
[[ "$PROCESSING" =~ ([^/]*)(/.*) ]]
[[ -s "${BASH_REMATCH[1]}${BASH_REMATCH[2]}/lib.sh" ]]
[[ -s "${BASH_REMATCH[1]}/Library${BASH_REMATCH[2]}/lib.sh" ]]
```
Moreover, the current code for library search and load seems to me quite hard to read so a rewrite is not that bad idea as well.

**Comment by psss** [comment]
I'd say if we expect the use case for a single library in a single repository to be common we should make it as easy and as short a possible. So `+1` from me to support naming `library(squid)` as well. For backward-compatibility, however, it would be good to provide a redirect wrapper inside the library similar the the [epel](https://github.com/beakerlib/distribution/blob/master/epel/lib.sh) one so that old tests which still have `library(squid/squid)` would work as well.

**Comment by sopos** [comment]
https://github.com/beakerlib/beakerlib/commit/40ec661b2173ba2f0a1f433a00b65ac8b7dc5a50
