### ISSUE TITLE
[RFE] upstream libraries

### ISSUE THREAD

**Issue by sopos** [beakerlib/beakerlib#7]
There's already a concept of libraries which can be sourced by rlImport function. But the infrastructure is left on user's infrastructure. This makes things harder while migrating tests from custom infrastructure to upstream.
There might be a dedicated repository here at github for libraries.
One idea is to have branches per library. It would also prevent prefix collisions. Beakerlib would than be able to search for specific libraries also in such repository.
Other way could be to create special organization where every library would have its own repository which would also allow them to have devel and other branches.

**Comment by sopos** [comment]
Ok, there appears a need for more generic, distro independent, way of libraries distribution.
There are currently three possible ways to achieve this using github or any other git-based solution, I can think of.

1. one repository under https://github.com/beakerlib, where each library is located in its own directory
    * pros
        * simple structure
        * all libraries at one place - easy mass updates if required
    * cons
        * more complicated downloading of a single library
        * worse maintainability
            * keep limited number of repo admins
            * a need to moderate each change to ensure the changes goes just to the desired library
            * a need to accept pull requests by low number of maintainers
1. one repository under https://github.com/beakerlib, where each library has its own dedicated branch
    * pros
        * better library isolation - lower risk of accidental changes to other libraries
        * possibility to allow direct push rights for the library owner
    * cons
        * worse maintainability
            * keep limited number of repo admins
            * a need to accept pull requests by low number of maintainers
1. multiple repositories under https://github.com/beakerlib-libraries, where each library has its own repo.
    * pros
        * better library isolation - lower risk of accidental changes to other libraries
        * complete control over the repo by library owner (rights delegation, pull requests handling, ...)
    * cons
        * a need of separate github organization so it is not so nicely tight to the beakerlib organization

I think the only really usable possibilities are 2 and 3.

**Comment by sopos** [comment]
@hegerj I think option 3 give us the best granularity in terms of permissions so I think it is a winner.

**Comment by hegerj** [comment]
@sopos How about separate repo for each library under https://github.com/beakerlib organization?

**Comment by sopos** [comment]
That would mean the beakerlib repo would be kind of outstanding there. But it is a possibility for sure.

**Comment by hegerj** [comment]
I don't think location of the libraries is especially important so either option 3 or the one I proposed in previous comment is fine by me.

**Comment by sopos** [comment]
As I'm thinking about it, the separate organization has also one more advantage - there might be different set of the org admins then for the beakerlib itself. So I'm still leaning to option 3 rather to option "4"

**Comment by tomato42** [comment]
I think number 2 would be very confusing to users, not to mention monitoring for bugs – it would quickly become very irritating for maintainers if they were getting 100 issue notifications and just one applicable to their library

side note: I don't know about other libraries, but at least our one is already public: https://github.com/redhat-qe-security/certgen and I'd prefer not to move it, so even if there is a project space for maintainers that want to share it, I think there should be an option for external libraries
maybe a definition file that points to the external repositories

**Comment by sopos** [comment]
> I think number 2 would be very confusing to users, not to mention monitoring for bugs – it would quickly become very irritating for maintainers if they were getting 100 issue notifications and just one applicable to their library
> 
good point, that's another con.
> side note: I don't know about other libraries, but at least our one is already public: https://github.com/redhat-qe-security/certgen and I'd prefer not to move it, so even if there is a project space for maintainers that want to share it, I think there should be an option for external libraries
> maybe a definition file that points to the external repositories

Right, I would like to make it flexible enough to allow also other locations to be configured via some env variable.
I thought about a list of URLs to point to a root where to find all the libraries. The option to directly point it to a specific library, makes sense as well.

**Comment by thrix** [comment]
I would opt for 3 also, definitely better then 2 from maintenance point of view. Branches should not be really misused as in 2 in my POW, would make contributors confused.

**Comment by sopos** [comment]
Thank you for your input. You've just confirmed my expectation.

**Comment by psss** [comment]
Agreed, separate repository for each library seems the best choice. Regarding the environment variable:

> Right, I would like to make it flexible enough to allow also other locations to be configured via some env variable.

Is this needed? What about adding support for specifying repository directly to the `rlImport` function?

    rlImport https://github.com/redhat-qe-security/certgen

Seems quite straightforward to me.

**Comment by psss** [comment]
Also the `beakerlib-libraries` organization could be used as the default space where libraries would be looked for, so for those you could only provide library name. Thoughts?

**Comment by sopos** [comment]
Yes and yes.
Yes, rlImport could be able to do direct referencing.
Yes, beakerlib-libraries is meant to be a default fallback is the library is not found anywhere else. Whoever, it might be useful to have an ability to define another such location in case someone would like to have its own bunch of libraries overriding the default ones.

**Comment by bachradsusi** [comment]
Direct reference would be definitely a step forward.

But it'd like to see an option to define relative import `rlImport selinux-policy/common` nad it would look for the import on a local filesystem, and if it's not available, it would download it from e.g. beakerlib-libraries. This way I could use downstream library version in my downstream test environment while upstream environment would use the upstream version using the same code

**Comment by sopos** [comment]
That's the intention. To et it work as now and add a fallback or a cascade of fallbacks to try until the library is found. It is still a question how the definition of the fallback destination should be defined, see https://github.com/beakerlib/beakerlib/issues/51.

**Comment by sopos** [comment]
There's one more thing. As it is obvious we want to have separate repo for each library we probably want to have it really pre library rather then per component as we are currently used to in downstream.
E.g.,instead of having repo `sudo` in which would be libraries `ldap` and `common`, there would be two repositories `sudo-ldap` and `sudo-common`, right?
So according to https://github.com/beakerlib/beakerlib/issues/51, the default fallback path would be
```
(.*)https://github.com/beakerlib-libraries/%{COMPONENT}-%{NAME}/raw/master/lib.yaml
```
rather than
```
(.*)https://github.com/beakerlib-libraries/%{COMPONENT}/raw/master/%{NAME}.yaml
```
Of course, this would be a default so a user defined location could de the latter as well.

**Comment by psss** [comment]
So it seems there is an agreement on a separate repo for each library. Thinking a bit about the naming. To me `https://github.com/beakerlib-libraries` sounds a little bit too long. What about some shorter version? It could be `https://github.com/beakerlibs` or even hosting libraries under the `beakerlib` organization in `https://github.com/beakerlib`. I guess for each repository under the same organization it is still possible to add individual contributors, right? And I guess there will be big overlap of those who will be admins of those organizations anyway. So the last option seems to me for now as the best one.

**Comment by lukaszachy** [comment]
I vote for hosting libraries in `beakerlib` project (where library maintainers will have rights just for their library). 
Can we have `library-` prefix for repository names? So in the project will be repo `beakerlib` for the framework itself and bunch of `library-*` with individual libraries. This prefix will be omitted from the name used in metadata but will be used for the github lookup (`library(firewalld/main)` -> `beakerlib/library-firewalld` repository)

**Comment by martinky82** [comment]
Correction: library(firewalld/main) -> beakerlib/library-firewalld/main (in the design of beakerlib libraries, there is a possibility of having more than one library for a component)

Or, we can drop this feature and settle on having just flat beakerlib libraries organization. Then, the /main part could and should be dropped altogether when using libraries from git.

Thoughts?

**Comment by psss** [comment]
Looking at the list of existing libraries it seems there is a bunch of those which use multiple libraries for a single component so we should probably keep that.

Regarding the `library-` prefix. I'm not sure. By default I would vote for a shorter version. Unless we expect there would be some other naming collisions in the github organization. If collisions are expected then I would rather choose a separate organization for libraries `beakerlibs` or `beakerlib-libraries`.

**Comment by sopos** [comment]
1) I would probably not use the `library-` prefix.
using one repository to the "component" with all the libraries in it is not ideal as the there might be different maintainers and different approach (imagine "component" distribution).
3) using project `beakerlib` is definitely an option and @psss is right that there will be probably significant overlap in admins of `beakerlib` and `beakerlib-libraries`. May be we can do some voting.

**Comment by kkaarreell** [comment]
I am not convinced that rlImport handling the library import from a different source is a good idea. It basically requires each test to do the download again, moreover it make more difficult to point tests to a different library location, e.g. a devel branch. Also, did you consider a concept that I would like to prevent such rlImport behavior despite it is written in the test?

**Comment by psss** [comment]
The current proposal is that it would be discover step's responsibility to fetch libraries and prepare them for testing. See psss/tmt/pull/277 for details and the first version of the feature. Note after yesterday's discussion the pull request is not completely up to date, I'm working on a refresh.

**Comment by kkaarreell** [comment]
@psss I didn't know this problem is tmt specific, I thought it should be an independent (generic) beakerlib feature. Anyway, if there is no demand for it outside the tmt world then even better. :-)

**Comment by sopos** [comment]
Yes, currently the implementation in beakerlib itself can be put to cold cases. And beakerlib will keep expecting the libraries to be in place already.
There's still a possibility to introduce this feature in future, if there is a need.

**Comment by sopos** [comment]
this is solved on the scheduler side
