### ISSUE TITLE
Add support for component/library/lib.sh in upward traversal

### ISSUE THREAD

**Issue by psss** [beakerlib/beakerlib#70]
As discussed in https://github.com/psss/tmt/issues/391 it would be good if library's `runtest.sh` is able to find its `lib.sh` during upward traversal even if the `Library` is not present in the path.

**Comment by sopos** [comment]
I think this should be covered by https://github.com/beakerlib/beakerlib/commit/a05d63c2dea22abcfb8e093d6fa885bf7cf42da7#diff-f18f830351594ecef2d24915a6cbbe38c451565c118c7839702b5fe5d2314b72R114

**Comment by sopos** [comment]
fixed by https://github.com/beakerlib/beakerlib/commit/40ec661b2173ba2f0a1f433a00b65ac8b7dc5a50
