### ISSUE TITLE
Support importing libraries from current working directory

### ISSUE THREAD

**Issue by psss** [beakerlib/beakerlib#94]
As discussed in psss/tmt/issues/391 it would be useful to be able to import beakerlib library from the same directory where the test is located. The proposed syntax is:

    rlImport .

This will simplify writing library self tests for cases when directory traversal does not detect the library.

**Comment by sopos** [comment]
Looking into the code I noticed that the libraries are search from the a test path or current path while resolving symlinks into the real path.
I wonder if this is really what we want as there may be the structure created using symlinks right to serve the test with the libraries of the required versions, e.g. various refs.

**Comment by sopos** [comment]
Actually using the current directory name should have the same effect, see https://github.com/beakerlib/ControlFlow/blob/sessions/SessionControl/runtest.sh

**Comment by sopos** [comment]
fixed by https://github.com/beakerlib/beakerlib/commit/484a44363e465c7d44a5fb5998fb0f9dedc74cc5
