### ISSUE TITLE
[RFE] rIsRHELLike()

### ISSUE THREAD

**Issue by AloisMahdal** [beakerlib/beakerlib#95]
Context
=======

As part of in-place upgrade testing initiative, we already have speial
tests that (simplified) will do *setup* on RHEL-N and *test* on RHEL-N+1.

A newer, initiative -- convert2rhel has similar needs: there we have
use cases for "upgrade" tests that start on CentOS and end on RHEL.

Both types of tests are identical in structure:

 *  get source distro (RHEL-7 / CentOS-7 / ...),
 *  set up -- here we use BeakerLib code,
 *  upgrade *or* convert (to RHEL-7 / ...)
 *  test -- here we use same BeakerLib code again,

and because some components are long-term stable in CLI and behavior,
even the *content* is often almost identical.

Hence, we want to re-use the code as much as possible.

But the CLI/behavior is not 100% *identical* - they need to code branch
per distro -- hence the use of `rlIsRHEL()` is common.

Problem
=======

When we try to take a test code that uses `rlIsRHEL` and re-use it in
a convert2rhel testing, we end up having to go to the code and change from

    if rlIsRHEL '>6'; then
    ...

to

    if rlIsRHEL '>6' || rlsCentOS '>6'; then
    ...

which can become really messy and confusing, especially if the `rlIsRHEL` condition is already part of 
a more complex boolean expression.

Furthermore, there's a perspective that we may want to run this on other
distros, eg. OracleLinux.  BeakerLib does not have `rlIsOracleLinux`
but I think you can see where this would go.

Solution
========

In most (not all, though) cases, the behavior of RHEL and RHEL-like
distro can be assumed to be identical.  In these cases, rlIsRHEL
could be effectively replaced by something like this:

    rlIsRHELLike() {
        #
        # True if rlIsRHEL $@ OR rlIsCentOS $@ would be true
        #
        rlIsCentOS "$@" && return 0
        rlIsRHEL   "$@" && return 0
        return 1
    }

This would make the code re-usable on CentOS without further complexity.

Furthermore, the `rlIsRHELLike` function could be easily extended to
support other RHEL forks  (where the major/minor assumption can be made),
making tests re-usable with no changes.

**Comment by AloisMahdal** [comment]
Note that the RFE could be probably justified by a far more generic context:  just re-using of RHEL tests on CentOS.  :-)

**Comment by sopos** [comment]
We already touched this topic in https://github.com/beakerlib/beakerlib/issues/47. Unfortunately there was not development done so far.

**Comment by sopos** [comment]
the plan was to implement `rlIsOS` and `rlIsOSLike` as described in https://github.com/beakerlib/beakerlib/issues/47#issuecomment-557101036

**Comment by sopos** [comment]
another variant to take into a consideration
```
NAME="Rocky Linux"
VERSION="8"
ID="rocky"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:rocky:rocky:8"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
CENTOS_MANTISBT_PROJECT="Rocky-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

**Comment by sopos** [comment]
latest Rocky Linux os-release looks better
```
NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

It is questionable how to handle a distro which provides just major version but the user is asking for a minor too, e.g. `rlIsRHELLike '8.4'`? That was the case of _Rocky Linux_ in its early stages and _CentOS_ as well.
In these cases we should either ignore minors or fail, I thing.

**Comment by hegerj** [comment]
In my opinion failing would be more "correct" resolution, however ignoring it would suit more use cases... not helping much, am I? :)

**Comment by sopos** [comment]
I agree (that you are not helping much :) that failing would be cleaner solution.

Considering the fact that CentOS 8 is always meant to the the latest one (so currently kind of 8.4) the `rlIsRHELLike '8.4'` should pass and `rlIsRHELLike '<8.4'` should fail but this is basically impossible to achieve as there's no way to know what is the currently released version, is there?

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
```
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

**Comment by hegerj** [comment]
I think so.
