### ISSUE TITLE
rlCheckMakefileRequires can't process require as `beakerlib >= 1.23`

### ISSUE THREAD

**Issue by lukaszachy** [beakerlib/beakerlib#96]
Command `rlCheckMakefileRequires` ends with `[ WARNING  ] :: requirement '1.23' not satisfied`.

File metadata.yaml contains
```yaml
require:
- beakerlib >= 1.23
```
I'd say that rlGetYAMLdeps doesn't quote string properly.

This was found in test suite of tmt run in https://github.com/psss/tmt/pull/667

**Comment by sopos** [comment]
It was not expected to use versioned requires at all. Beakerlib is not able to assert package version at this point neither.

**Comment by sopos** [comment]
The feature is out. Now, just make sure the package is deployed wherever you need.
