### ISSUE TITLE
rlRun -s should be able to reuse the tempfile

### ISSUE THREAD

**Issue by thrix** [beakerlib/beakerlib#99]
Seems in some cases we would like if the tempfile created by rlRun to be reused, so we can cleanup easily with one command. Now it always creates a new file.

This can be a new option to `rlRun` for example, where we pass in the tempfile for example.

```
rlRun "tmpfile=$(mktemp)"
rlRun -s -f $tmpfile "...."
rlAssertGrep "..." $rlRun_LOG
rlRun -s -f $tmpfile "...."
rlAssertGrep "..." $rlRun_LOG
rlRun "rm -f $rlRun_LOG"
```

cc @psss @sopos

**Comment by sopos** [comment]
Adding a new option may be a solution but it does not solve the current tests.
I wan thinking of a compromise solution some time ago. It would be to gather the files generated and clean them all the the end of the test.
In theory there should not be aby usage of such files after _rlJournalEnd_ so me idea was to keep the files list and simply remove the files in the _rlJournalEnd_ function. This should break minimum of the test cases, if any, and it would also improve the cleanup for all existing tests.

@hegerj , what's your opinion on this?

**Comment by hegerj** [comment]
I cannot think of a way how could one use the temp file after test ends so I guess it is ok.

**Comment by sopos** [comment]
implemented by https://github.com/beakerlib/beakerlib/pull/106
